name: padeltrax_app
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1 # Adjusted to a more stable version

flutter:
  uses-material-design: true

  assets:
    - assets/images/padeltrax_logo.png
    - assets/images/profile.png
