// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOJfsG7_lTgtmBNPdJVB4b-vPdahG4LxU',
    appId: '1:1040892024883:web:11750f6de0d0ee077c6b46',
    messagingSenderId: '1040892024883',
    projectId: 'padel-trax-killwd',
    authDomain: 'padel-trax-killwd.firebaseapp.com',
    storageBucket:
        'padel-trax-killwd.appspot.com', // Ensure correct bucket format for web
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMpwBZbDi6AFOQEheg1TOzG0aNwg2dfHc',
    appId: '1:1040892024883:android:a8c559db42d7c1f07c6b46',
    messagingSenderId: '1040892024883',
    projectId: 'padel-trax-killwd',
    storageBucket: 'padel-trax-killwd.appspot.com', // Unified bucket format
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN1KqJizZOmsWPZ1x8_zcTyfVP6Ps6F1U',
    appId: '1:1040892024883:ios:0c6605a1d3d04f0b7c6b46',
    messagingSenderId: '1040892024883',
    projectId: 'padel-trax-killwd',
    storageBucket: 'padel-trax-killwd.appspot.com',
    androidClientId:
        '1040892024883-0vck8qpbqa0b4dod3nbs0ehiisiunaog.apps.googleusercontent.com',
    iosBundleId:
        'com.mycompany.padeltrax', // Match iOS bundle ID to Firebase console
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN1KqJizZOmsWPZ1x8_zcTyfVP6Ps6F1U',
    appId: '1:1040892024883:ios:0c6605a1d3d04f0b7c6b46',
    messagingSenderId: '1040892024883',
    projectId: 'padel-trax-killwd',
    storageBucket: 'padel-trax-killwd.appspot.com',
    androidClientId:
        '1040892024883-0vck8qpbqa0b4dod3nbs0ehiisiunaog.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.padeltrax', // Match macOS bundle ID
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOJfsG7_lTgtmBNPdJVB4b-vPdahG4LxU',
    appId: '1:1040892024883:web:a61c692fc69991667c6b46',
    messagingSenderId: '1040892024883',
    projectId: 'padel-trax-killwd',
    authDomain: 'padel-trax-killwd.firebaseapp.com',
    storageBucket: 'padel-trax-killwd.appspot.com',
  );
}
